# Generated by Django 4.1.2 on 2022-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdata',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listdata',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listdata',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
