# Generated by Django 4.1.2 on 2022-10-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_listdata_user_alter_listdata_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdata',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
