# Generated by Django 4.1.2 on 2022-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_listdata_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdata',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
