# Generated by Django 4.1.2 on 2022-10-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_listdata_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdata',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
